events {}

http {
    server {
        listen 80;
        http2 on; 

        # REST
        location /api/ {
            proxy_pass http://app:8080/;
        }

        # gRPC (IMPORTANT CHANGE)
        location / {
            grpc_pass grpc://app:9090;
        }
    }
}